#!/bin/bash

export KANON_OPT=/opt/kanon
export KANON_VAR=/var/opt/kanon

if [ -f /etc/debian_version ]
then
    OS='debian'
    APACHE_USER=www-data
elif [ -f /etc/redhat-release ]
then
    APACHE_USER=apache
    CHK=`egrep "CentOS release 5|Red Hat Enterprise Linux .* 5" /etc/redhat-release`
    if [ "$CHK" != '' ]
    then
        OS='rhel5'
    else
        OS='rhel6'
    fi
else
    echo "サポートされていないOSです。"
    echo "現在サポートされいているOSは、"
    echo ""
    echo "  * Ubuntu 10.10 Server"
    echo "  * Debian GNU/Linux, GNU/kFreeBSD 6.0"
    echo "  * RedHat Enterprise Linux 6.0"
    echo "  * Oracle Enterprise Linux 6.0"
    echo "  * CentOS 5.x (Experimental)"
    echo ""
    echo "です。"
    exit
fi

if [ "$USER" != 'root' ]
then
    echo "rootでコマンドを実行してください。"
fi


if [ -d /opt/kanon ]
then
    echo "=========================================================================="
    echo "注意！！ このマシンには既にKanonがインストールされているかも。確認してね♪"
    echo "=========================================================================="
fi
echo ""
echo "このコマンドはKanonをインストールするよ。"
echo "既にkanonインストールされている場合は、上書きされて消えちゃうの。"
echo -n "Kanonをインストールする?(y/n) "
read YN

if [ "$YN" != "y" ]
then
    echo "インストールを中断したよ。"
    exit
fi

### install ubuntu package 
case $OS in
    debian)
        apt-get update 
        apt-get -y install `cat pkglist.debian` 
        ;;
    rhel6)
        yum -y install `cat pkglist.rhel6`
        ;;
    rhel5)
        # TODO
        # アップグレードしたパッケージのリポジトリの設定(http://kanon.ultimania.org/pkg/centos5)と
        #   yum -y install subversion-1.6.15-1.el5の
        #   yum -y install mod_dav_svn-1.6.15-1.el5
        # の実行
        # Add EPEL Repositories. For python26, python26-devel, python26-mod_wsgi.
        EPEL_RPM_URL="http://download.fedora.redhat.com/pub/epel/5/i386/epel-release-5-4.noarch.rpm"
        wget $EPEL_RPM_URL
        rpm -Uvh epel-release-5-4.noarch.rpm
        rm -f epel-release-5-4.noarch.rpm
        yum -y install `cat pkglist.rhel5`
        ;;
    *)
        ;;
esac

### install files
cp -fr opt/* /opt
if [ "$OS" = "rhel5" ]
then
    # FIXME CentOS 5.x では n オプションがないため 強制上書きになってしまう.
    cp -fr etc/* /etc
else
    cp -frn etc/* /etc
fi


### setup configuration
python2.6 resource/virtualenv.py /opt/kanon
source /opt/kanon/bin/activate

## setup sitecustomize for python
if [ -f /etc/python2.6/sitecustomize.py ]
then
    CHK=`grep "setdefaultencoding" /etc/python2.6/sitecustomize.py`
    if [ "$CHK" = '' ]
    then 
        cat opt/kanon/lib/python2.6/site-packages/sitecustomize.py >> /etc/python2.6/sitecustomize.py
    fi
fi


if [ "$OS" = "rhel5" ]
then
    # Install Subversion.
    if [ "$UPGRADE_SVN" = "y" ]
    then
        ./subversion-16-upgrade.sh
    else
        yum -y install subversion mod_dav_svn
    fi
    # Install Extra Package for CentOS 5.X
    easy_install "mercurial==1.7.3"
    easy_install bzr
    easy_install pygments
fi

easy_install http://svn.edgewall.org/repos/genshi/tags/0.6.0/
easy_install http://ftp.edgewall.com/pub/babel/Babel-0.9.5.zip
easy_install http://www.i-act.co.jp/project/products/downloads/Trac-0.12.2.ja1.zip
easy_install xlrd
easy_install https://github.com/hvr/trac-git-plugin/zipball/v0.12.0.5
# bzr co lp:trac-bzr /tmp/trac-bzr-install
#easy_install --prefix /opt/kanon /tmp/trac-bzr-install
#rm -fr /tmp/trac-bzr-install


### install trac plugins
easy_install http://svn.edgewall.com/repos/trac/plugins/0.12/mercurial-plugin

#resource/pluginsディレクトリのプラグインをインストール
pushd .

cd resource/trac-plugins
for i in `ls -1 .`
do
    cd $i;python setup.py install
    cd ..
done
cd ../..

# install plugins from web site
rm -fr /tmp/kanon_build
for i in `cat pluginlist`
do
    cd /tmp
    svn co $i kanon_build
    cd kanon_build
    python setup.py install
    cd ..
    rm -fr kanon_build
done
popd


### setup apache and restart
case $OS in
    debian)
        cp resource/trac_hook.py /usr/lib/python2.6/dist-packages/bzrlib/plugins
        if [ ! -f /etc/apache2/sites-available/kanon ]
        then
            cp resource/httpd.conf /etc/apache2/sites-available/kanon
        fi
        a2enmod expires
        a2enmod auth_digest
        a2enmod dav_fs
        a2ensite kanon
        service apache2 stop
        service apache2 start
        ;;
    rhel6)
        mkdir -p /usr/lib/python2.6/site-packages/bzrlib/plugin
        cp resource/trac_hook.py /usr/lib/python2.6/site-packages/bzrlib/plugin
        if [ ! -f /etc/httpd/conf.d/kanon.conf ]
        then
            cp resource/httpd.conf /etc/httpd/conf.d/kanon.conf
        fi
        echo 0 > /selinux/enforce
        echo "SELinuxが無効化されました"
        service httpd stop
        service httpd start
        ;;
    rhel5)
        mkdir -p /var/opt/kanon/trac/.egg-cache
        chown $APACHE_USER:$APACHE_USER -R /var/opt/kanon/trac/.egg-cache/
        mkdir -p /usr/lib/python2.6/site-packages/bzrlib/plugin
        cp resource/trac_hook.py /usr/lib/python2.6/site-packages/bzrlib/plugin
        if [ ! -f /etc/httpd/conf.d/kanon.conf ]
        then
            cp resource/httpd.conf /etc/httpd/conf.d/kanon.conf
        fi
        echo 0 > /selinux/enforce
        echo "SELinuxが無効化されました"
        mv /etc/httpd/conf.d/python.conf /etc/httpd/conf.d/python.conf.disabled
        service httpd stop
        service httpd start
        ;;
    *)
        ;;
esac


# データディレクトリが存在しない場合作成
if [ ! -d "$KANON_VAR/trac" ]
then
    mkdir -p "$KANON_VAR/trac"
fi

if [ ! -d "$KANON_VAR/hg" ]
then
    mkdir -p "$KANON_VAR/hg"
fi

if [ ! -d "$KANON_VAR/bzr" ]
then
    mkdir -p "$KANON_VAR/bzr"
fi

if [ ! -d "$KANON_VAR/svn" ]
then
    mkdir -p "$KANON_VAR/svn"
fi

if [ ! -d "$KANON_VAR/git" ]
then
    mkdir -p "$KANON_VAR/git"
fi

# setup SampleProject
if [ ! -d "$KANON_VAR/trac/SampleProject" ]
then
    /opt/kanon/bin/kanon-create-project SampleProject svn default
    svn import SampleProject file:///var/opt/kanon/svn/SampleProject/ -m "initial import."
    chown $APACHE_USER.$APACHE_USER -R /var/opt/kanon/svn/SampleProject
fi

echo "Kanon Team Conductorのインストールが完了しました。"
echo $KANON_OPT"/bin/kanon-create-project コマンドでプロジェクトを作成してください。"
